# Maki template version: 1.0

version: '3.2'

volumes:
  db-data:

services:
  frontend:
    container_name: frontendLearn
    build:
      context: .
      dockerfile: .deploy/docker/frontend/Dockerfile
    volumes:
      - ./.deploy/docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - backend
    ports:
      - 8015:80

  backend:
    container_name: backendLearn
    build:
      context: .
      dockerfile: .deploy/docker/backend/Dockerfile
    env_file:
        - ./.env
    volumes:
      - .:/app


  db:
    container_name: dbLearn
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: learn
    volumes:
      - db-data:/var/lib/postgresql/data
